import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Trello Clone',
  description: 'Generated by Arturo Miranda',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6F7'>
        {children}
        <Modal />
      </body>
    </html>
  )
}
